#!/bin/bash

function register_providers {
    for provider in $(ls providers/*.sh); do
        provider_name=$(basename $provider .sh)
        source $provider
        if [ "$provider_registered" -eq 1 ]; then
            echo $provider_name registered
            # HOW TO REGISTER?
        else
            echo $provider_name not found
        fi
    done
}

function usage {
    # TODO
    echo "Usage"
}

function search {
    # TODO
    echo "Search" $@
}

case "$1" in
    search )
        shift
        search $@
        ;;
    register-providers )
        shift
        register_providers
    ;;
    * )
        usage
        ;;
esac
