#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
# -*- coding: utf-8 -*-
__author__ = 'nickl-'
from aero.__version__ import __version__

def run():
    from aero import main
    return main()

if __name__ == "__main__": run()
