#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'nickl-'
__version__ = '0.0.1'




def run():
#    import aero
#    aero.__path__ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    from aero import main
    return main()

if __name__ == "__main__": run()
#    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#    ## FIXME: this is kind of crude; if we could create a fake pip
#    ## module, then exec into it and update pip.__path__ properly, we
#    ## wouldn't have to update sys.path:
#    sys.path.insert(0, base)
#    import pip
#    return pip.main()
#
#
#if __name__ == '__main__':
#    exit = run()
#    if exit:
#        sys.exit(exit)
#
